w4/w4d2/Cats/config/routes.rb
Rails.application.routes.draw do

  resources :cats

end

w4/w4d2/Cats/app/models/cat.rb
class Cat < ActiveRecord::Base

  COLORS = %w(black white orange)


  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :name, uniqueness: true
  validates :color, inclusion: {in: COLORS }
  validates :sex, inclusion: { in: ["M","F"]}

  def age
    age = Date.today.year - self.birth_date.year
    age -= 1 if Date.today < self.birth_date + age.years
    age
  end

end

w4/w4d2/Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w4/w4d2/Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end

  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end

end

w4/w4d2/Cats/app/helpers/cats_helper.rb
module CatsHelper
end

w4/w4d2/Cats/app/views/cats/_form.html.erb
<% if action == :edit %>
<% action_url = cat_url(cat) %>
<% else %>
<% action_url = cats_url %>
<% end %>

<form action= "<%= action_url %>" method="post">
  <% if action == :edit %>
  <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label> &nbsp;
  <input id=name type="text" name="cat[name]" value= "<%= cat.name %>"><br><br>

  <label for="sex">Sex</label> &nbsp;
  <input type="radio" name="cat[sex]" value="M" <% if action == :new %> <%= "checked" %> <% else %><%= cat.sex == "M" ? "checked" : "" %> <% end %> > Male
  <input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %> > Female<br><br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">

    <option disabled  <%= cat.color ? "" :  "selected" %> >--Option--</option>

    <option value="black" <%= cat.color == "black" ? "selected" : "" %> >Black</option>


    <option value="white"<%= cat.color == "white" ? "selected" : "" %> >White</option>

    <option value="orange" <%= cat.color == "orange" ? "selected" : "" %> >Orange</option>

  </select><br><br>
    <label for="date">Birth Date</label>
    <input type="date" name="cat[birth_date]" value= "<%= cat.birth_date %>"><br><br>

  <label for="description">Description</label>
    <textarea name="cat[description]">
      <%= cat.description %>
    </textarea><br><br>

  <input type="submit" value=" <%=  (action == :edit) ? "Update Cat" : "Create Cat" %>">
</form>

w4/w4d2/Cats/app/views/cats/edit.html.erb
<h1>New Cat</h1>


<%= render "form", cat: @cat, action: :edit  %>

w4/w4d2/Cats/app/views/cats/index.html.erb
<h1>ALL OF THE CATS IN THE WORLD</h1>


<ul>
  
  <%  @cats.each do |cat| %>

  <li>  <%= link_to "#{cat.name}", cat_url(cat) %> </li>
    <% end %>

</ul>

w4/w4d2/Cats/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render "form", action: :new, cat: @cat  %>

w4/w4d2/Cats/app/views/cats/show.html.erb
<li><%= link_to "All", cats_url %></li>
<table>
  <caption> <%= @cat.name %> </caption>
  <tr>
    <th>attributes</th>
    <th>values</th>
  </tr>
  <tr>
    <td> Age </td>
    <td> <%= @cat.age %> </td>
  </tr>
  <tr>
    <td> Birth Date </td>
    <td> <%= @cat.birth_date %> </td>
  </tr>
  <tr>
    <td> Color </td>
    <td> <%= @cat.color %> </td>
  </tr>
  <tr>
    <td> Sex </td>
    <td> <%= @cat.sex %> </td>
  </tr>
</table>

w4/w4d2/Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>