w4/w4d5/RedditOnRails/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :show, :create]

  resource :session, only: [:create, :new, :destroy]

  resources :subs do
    resources :posts, only: [:index]
  end

  resources :posts, except: :index

end

w4/w4d5/RedditOnRails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :sub
end

w4/w4d5/RedditOnRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts

end

w4/w4d5/RedditOnRails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    foreign_key: :author_id


  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64(128)
    self.save
    self.session_token
  end

  private

    def ensure_session_token
      self.session_token ||= SecureRandom.urlsafe_base64(128)
    end
end

w4/w4d5/RedditOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def logged_in?
    !!(current_user)
  end

  def logout!
    current_user.reset_session_token
    session[:token] = nil
  end

  def login!(user)
    session[:token] = user.reset_session_token
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def user_params
    params.require(:user).permit(:password, :username)
  end
end

w4/w4d5/RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def create
    @post = Post.new(post_params)
    redirect_to sub_url(@post.sub)
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def edit
    @post = Post.find_by(id: params[:id])
    @subs = Sub.all
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update
      redirect_to sub_url(@post.author)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    post = Post.find_by(id: params[:id])
    flash[:messages] = ["#{post.title} deleted!"]
    post.destroy
    redirect_to subs_url
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end

end

w4/w4d5/RedditOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])

    if @user
      login!(@user)
      flash[:messages] = ["Welcome Back!"]
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def new
    render :new
  end

  def destroy
    logout!
    redirect_to new_session_url
  end


end

w4/w4d5/RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to subs_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end


  def show
    @posts = Post.where(sub_id: params[:id])
    @sub = Sub.find_by(id: params[:id])
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update
      redirect_to subs_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    sub = @sub.find_by(id: params[:id])
    sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

w4/w4d5/RedditOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end


end

w4/w4d5/RedditOnRails/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_tok
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

w4/w4d5/RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

w4/w4d5/RedditOnRails/app/helpers/session_helper.rb
module SessionHelper
end

w4/w4d5/RedditOnRails/app/helpers/subs_helper.rb
module SubsHelper
end

w4/w4d5/RedditOnRails/app/helpers/users_helper.rb
module UsersHelper
end

w4/w4d5/RedditOnRails/app/views/application/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<% if flash[:messages] %>
  <% flash[:messages].each do |message| %>
    <%= message %>
  <% end %>
<% end %>

w4/w4d5/RedditOnRails/app/views/application/_login_form.html.erb
<form action="<%= destination_url %>" method="post">
  <%= auth_tok %>

<label for='username'>Username</label>
<input id='username' type="text" name="user[username]"/>

<br/><br/>

<label for='password'>Passowrd</label>
<input id='password' type="text" name="user[password]"/>

<br/><br/>

<input type='submit' value="<%= button_text %>">
</form>

w4/w4d5/RedditOnRails/app/views/application/_login_nav.html.erb
<% if logged_in? %>
  <%= button_to 'logout', session_url, method: :delete %>
<% else %>
  <% unless request.env['PATH_INFO'] == '/session/new' %>
    <%= button_to 'log in', new_session_url, method: :get %>
  <% end %>
  <% unless request.env['PATH_INFO'] == '/users/new'%>
    <%= button_to 'sign up', new_user_url, method: :get %>
  <% end %>
<% end %>

w4/w4d5/RedditOnRails/app/views/application/_posts_form.html.erb
<form action="<%= destination_url %>" method="post">
  <%= auth_tok %>

<label for='title'>Title</label>
<input id='title' type="text" name="post[title]" value="<%= @post.title %>"/>

<br/><br/>

<label for='content'>content</label>
<textarea id='content' name="post[content]">
  <%= @post.content %>
</textarea>

<br/><br/>

<select name="post[sub_id]">
  <% @subs.each do |sub| %>
   <option value="<%= sub.id %>" <%= "checked" if @post.sub_id == sub.id %>>
     <%= sub.title %>
   </option>
   <% end %>
</select>
<br/><br/>

<input type='submit' value="<%= button_text %>">
</form>

w4/w4d5/RedditOnRails/app/views/application/_subs_form.html.erb
<form action="<%= destination_url %>" method="post">
  <%= auth_tok %>

<label for='title'>Title</label>
<input id='title' type="text" name="sub[title]" value="<%= @sub.title %>"/>

<br/><br/>

<label for='description'>description</label>
<textarea id='description' name="sub[description]">
  <%= @sub.description %>
</textarea>

<br/><br/>

<input type='submit' value="<%= button_text %>">
</form>

w4/w4d5/RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'login_nav' %>
<%= render partial: 'errors' %>

<%= yield %>

</body>
</html>

w4/w4d5/RedditOnRails/app/views/session/new.html.erb
<h1> Log in!</h1>

<%= render partial: 'login_form', locals: {
                                    destination_url: session_url,
                                    button_text: 'log in' } %>